version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./app/data:/app/data # per i file upload
      - ./app/database.db:/app/database.db  # per il DB SQLite persistente
